
# yum.qa.lab/ecosystem - a mostly-empty directory that only contains a symlink redhat -> ../opensource
# This trick gets around some of the hard-coding in the process.

packer build --only=sandbox-base --var 'mapr_spark_version=0' --var 'mapr_hue_version=0' --var 'mapr_hbase_version=' --var 'mapr_pig_version=0' --var 'mapr_oozie_version=0' --var 'mapr_hcatalog_version=0' --var 'mapr_flume_version=0' --var 'mapr_hive_version=' --var 'mapr_mahout_version=0' --var 'mapr_drill_version=' --var 'mapr_sqoop_version=0' --var 'mapr_version=4.1.0' --var 'mapr_core_repo_url=http://package.mapr.com/releases' --var 'mapr_eco_repo_url=http://yum.qa.lab/ecosystem' --var mapr_banner_url=http://%s:8047/ --var 'mapr_banner_name=MapR-Sandbox-For-Apache-Drill-1.0.0' mapr-sandbox.json

packer build --only=sandbox --var 'mapr_spark_version=0' --var 'mapr_hue_version=0' --var 'mapr_hbase_version=' --var 'mapr_pig_version=0' --var 'mapr_oozie_version=0' --var 'mapr_hcatalog_version=0' --var 'mapr_flume_version=0' --var 'mapr_hive_version=' --var 'mapr_mahout_version=0' --var 'mapr_drill_version=' --var 'mapr_sqoop_version=0' --var 'mapr_version=4.1.0' --var 'mapr_core_repo_url=http://package.mapr.com/releases' --var 'mapr_eco_repo_url=http://yum.qa.lab/ecosystem' --var mapr_banner_url=http://%s:8047/ --var 'mapr_banner_name=MapR-Sandbox-For-Apache-Drill-1.0.0' mapr-sandbox.json

packer build --only=sandbox-vmware --var 'mapr_spark_version=0' --var 'mapr_hue_version=0' --var 'mapr_hbase_version=' --var 'mapr_pig_version=0' --var 'mapr_oozie_version=0' --var 'mapr_hcatalog_version=0' --var 'mapr_flume_version=0' --var 'mapr_hive_version=' --var 'mapr_mahout_version=0' --var 'mapr_drill_version=' --var 'mapr_sqoop_version=0' --var 'mapr_version=4.1.0' --var 'mapr_core_repo_url=http://package.mapr.com/releases' --var 'mapr_eco_repo_url=http://yum.qa.lab/ecosystem' --var mapr_banner_url=http://%s:8047/ --var 'mapr_banner_name=MapR-Sandbox-For-Apache-Drill-1.0.0' mapr-sandbox.json
