#!/bin/bash
#
# chkconfig: 35 99 15
# description: Mapr Demo Startup
# startup script

SCRIPTS_PATH="/opt/startup"
NAME="_MAPR_BANNER_NAME_"
LOG="/var/log/startup_script.log"
HADOOP_VERSION="_HADOOP_VERSION_"
OOZIE_VERSION="_MAPR_OOZIE_VERSION_"
HUE_VERSION="_MAPR_HUE_VERSION_"
HIVE_VERSION="_MAPR_HIVE_VERSION_"
HTTPFS_VERSION="1.0"

#HIVE_VERSION=`echo "${HIVE_VERSION}" | awk -F. '{ printf("%s.%s", $1,$2); }`
#HUE_VERSION=`echo "${HUE_VERSION}" | awk -F. '{ printf("%s.%s.%s",$1,$2,$3); }`
#OOZIE_VERSION=`echo "${OOZIE_VERSION}" | awk -F. '{ printf("%s.%s.%s", $1,$2,$3); }`

case "$1" in
start)
    printf "%-50s\n" "Starting $NAME..." | tee -a $LOG
    
    echo "" > /etc/resolv.conf

    printf "%-50s\n" "Updating IP..." | tee -a $LOG
    bash $SCRIPTS_PATH/gen_hosts.sh
   
    sed -i 1i"nameserver 8.8.8.8" /etc/resolv.conf
    if [ -d "/opt/mapr" ]; then 
    printf "%-50s\n" "Bringing up VM..." | tee -a $LOG

    if [ -f "/opt/mapr/hadoop/hadoop-$HADOOP_VERSION/etc/hadoop/core-site.xml" ]; then
    cp -rf $SCRIPTS_PATH/core-site.xml /opt/mapr/hadoop/hadoop-$HADOOP_VERSION/etc/hadoop/core-site.xml
    #cp -rf $SCRIPTS_PATH/mapred-site.xml /opt/mapr/hadoop/hadoop-$HADOOP_VERSION/etc/hadoop/mapred-site.xml
    fi

    if [ -d "/opt/mapr/hadoop/hadoop-$HADOOP_VERSION/etc/hadoop" ]; then
    cp -rf $SCRIPTS_PATH/yarn-site-2.5.1-mapr-1503.xml /opt/mapr/hadoop/hadoop-$HADOOP_VERSION/etc/hadoop/yarn-site.xml
    fi

    echo 0 > /proc/sys/kernel/hung_task_timeout_secs

    if [ -f "/opt/mapr/oozie/oozie-$OOZIE_VERSION/conf/oozie-site.xml" ]; then
    cp -rf $SCRIPTS_PATH/oozie-site.xml /opt/mapr/oozie/oozie-$OOZIE_VERSION/conf/oozie-site.xml
    fi
    
    if [ -d "/opt/mapr/hue/hue-$HUE_VERSION" ]; then
    cp -rf $SCRIPTS_PATH/hue.ini /opt/mapr/hue/hue-$HUE_VERSION/desktop/conf/hue.ini 
    cp -f /opt/mapr/hue/hue-$HUE_VERSION/desktop/libs/hadoop/java-lib/hue-plugins-*.jar /opt/mapr/hadoop/hadoop-$HADOOP_VERSION/lib/
    fi 

    if [ -f "/opt/mapr/httpfs/httpfs-$HTTPFS_VERSION/etc/hadoop/httpfs-site.xml" ]; then
    cp -rf $SCRIPTS_PATH/httpfs-site.xml /opt/mapr/httpfs/httpfs-$HTTPFS_VERSION/etc/hadoop/httpfs-site.xml
    fi    
   
    if [ -f "/opt/mapr/hive/hive-$HIVE_VERSION/conf/hive-site.xml" ]; then
    cp -rf $SCRIPTS_PATH/hive-site.xml /opt/mapr/hive/hive-$HIVE_VERSION/conf/hive-site.xml
    cp -f /opt/mapr/hive/hive-$HIVE_VERSION/conf/warden.hivemeta.conf /opt/mapr/conf/conf.d/warden.hivemeta.conf
    fi

    service mapr-warden start

    printf "%-50s\n" "Waiting for MapR services to come up..." | tee -a $LOG
    sleep 60 
    su - mapr -c "jps | grep CommandServer"
    if [ $? -ne 0 ];then
    printf "%-50s\n" "Still waiting for MapR services to come up..." | tee -a $LOG
    sleep 60  
    fi
    fi
    su - mapr -c "jps | grep CommandServer"
    if [ $? -ne 0 ];then
    python $SCRIPTS_PATH/error.py
    else
    python $SCRIPTS_PATH/welcome.py
    maprcli volume create -name tables -path /tables
    fi

;;
stop)
    date >> $LOG
    service mapr-warden stop >> $LOG 2>&1
    service mapr-zookeeper stop >> $LOG 2>&1
;;

restart)
    service mapr-zookeeper restart >> $LOG 2>&1
    service mapr-warden restart >> $LOG 2>&1
;;

*)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
